### ISSUE TITLE
Blog post doesn't work well on dark mode

### ISSUE THREAD

**Issue by DurimDelilaj** [gethyas/doks#1082]
## Description
Blog post i bugged in dark mode

### Steps to reproduce

1) Click on blog
2) Turn on dark mode

### Expected result

The text of the post is white

### Actual result

The text of the post is black

### Environment

{
  '@hyas/doks': '0.5.0',
  npm: '9.8.1',
  node: '18.17.1',
  acorn: '8.8.2',
  ada: '2.5.0',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '6.0.11',
  modules: '108',
  napi: '9',
  nghttp2: '1.52.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.10+quic',
  simdutf: '3.2.12',
  tz: '2023c',
  undici: '5.22.1',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.18',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13.1-motley'
}
![Screenshot 2023-08-16 160933](https://github.com/h-enk/doks/assets/114028187/0b5eb8a8-9555-43d6-a76d-f14996aae8fd)

**Comment by h-enk** [comment]
Can't reproduce — see https://doks.netlify.app/blog/

Do you have a repo you could share?
