### ISSUE TITLE
Mermaid / Kate import error

### ISSUE THREAD

**Issue by jollydodo** [gethyas/doks#1132]
I'm getting similar issues to this: https://github.com/gethyas/doks/issues/560

Steps te replicate: 
System: Mac OS Ventura 13.1

`JSBUILD: failed to transform "js/mermaid.js" (text/javascript): [1;36m"/development/github/fablab-docs/node_modules/@hyas/doks-core/assets/js/mermaid.js:1:20"[0m: Could not resolve "mermaid" `

I get the same error (but then with katex) when enabling katex in the params.toml. 

A fresh clone on a windows machine gives me the same errors when trying to use mermaid in a markdown file and then trying to build. 

**Environment:**

`{
  'fablab-docs': '0.0.0',
  npm: '9.6.4',
  node: '20.0.0',
  acorn: '8.8.2',
  ada: '2.0.0',
  ares: '1.19.0',
  brotli: '1.0.9',
  cldr: '42.0',
  icu: '72.1',
  llhttp: '8.1.0',
  modules: '115',
  napi: '8',
  nghttp2: '1.52.0',
  openssl: '1.1.1t',
  simdutf: '3.2.7',
  tz: '2022e',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.16',
  v8: '11.3.244.4-node.3',
  zlib: '1.2.11'
}
(fablab_docs) niels@MBP-van-Niels fablab-docs % hugo version
hugo v0.101.0+extended darwin/arm64 BuildDate=unknown`

**Comment by jollydodo** [comment]
Katex was fixed by switching to the Math API in a new Hyas version. Mermaid unfortunately still has the same problem.

**Comment by h-enk** [comment]
Mermaid is supported with Doks [v1.2.0](https://github.com/gethyas/doks/releases/tag/v1.2.0) using the free [Kroki](https://kroki.io/) service.
