### ISSUE TITLE
Mermaid Rendering Issue with GitHub Pages

### ISSUE THREAD

**Issue by HusenjanDev** [gethyas/doks#1190]
## Description

Mermaid feature seems to have a bug with GitHub Pages.

### Steps to reproduce

Render the gethyas/doks page with the following command:

`npm run build`

Upload the files inside the public folder to GitHub Pages and the mermaid won't show up.

![image](https://github.com/gethyas/doks/assets/88688451/954a82e4-8aa8-42a0-bc94-a9c4b535702a)

### Expected result

The following diagram should show up.

![image](https://github.com/gethyas/doks/assets/88688451/a46b65e7-4fc2-46d0-a61d-0b09efe80dc5)

### Actual result

Instead the mermaid doesn't show up.

![image](https://github.com/gethyas/doks/assets/88688451/954a82e4-8aa8-42a0-bc94-a9c4b535702a)

In the inspect elements the mermaid file cannot be found.

![image](https://github.com/gethyas/doks/assets/88688451/7f982505-48cd-40b0-b52a-71c3c0bd8f1d)

### Environment

```
> hyas-project@0.0.0 preinfo
> npm version

{
  'hyas-project': '0.0.0',
  npm: '10.2.4',
  node: '21.5.0',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.24.0',
  base64: '0.5.1',
  brotli: '1.1.0',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '9.1.3',
  modules: '120',
  napi: '9',
  nghttp2: '1.58.0',
  openssl: '3.2.0',
  simdjson: '3.6.2',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.28.2',
  unicode: '15.0',
  uv: '1.47.0',
  uvwasi: '0.0.19',
  v8: '11.8.172.17-node.18',
  zlib: '1.2.12'
}

> hyas-project@0.0.0 info
> npm list

hyas-project@0.0.0 /Users/redacted/Documents/hyas-project
├── @hyas/doks-core@1.3.0
├── @hyas/images@2.0.3
├── @hyas/inline-svg@1.0.5
├── @hyas/seo@2.1.0
├── @tabler/icons@2.47.0
├── exec-bin@1.0.0
├── gethyas@2.2.2
├── hugo-installer@4.0.1
└── shx@0.3.4


> hyas-project@0.0.0 postinfo
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended darwin/arm64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio
```

**Comment by h-enk** [comment]
Closing — reopen if necessary
