### ISSUE TITLE
SEO title not working when updating to doks-core 1.3.0

### ISSUE THREAD

**Issue by caueobici** [gethyas/doks#1191]
## Description

I was using @hyas/doks-core 1.1.1 and SEO title was working fine (the <title> tag content was changed)

When I updated to @hyas/doks-core 1.3.0 it was not working anymore, if i change the SEO title, nothing changes in the HTML.

### Steps to reproduce

1. Create a page with SEO title

```md
---
title: "Test"
description: ""
[...]
seo:
  title: "Test 2"
  description: ""
  canonical: ""
  noindex: false
---

asdasd
```

2. Run the server using @hyas/doks-core@1.1.1

See that the page title is changed to "Test 2"

3. Run the server using @hyas/doks-core@1.3.0

See that the page title is not changed

### Expected result

The <title> tag content should be changed with the content specified in SEO title. 

### Actual result

Nothing was changed in the webpage.

I don't know if I am being dumb but it seems like a bug, let me know if i am missing something here

**Comment by h-enk** [comment]
Did you also update `@hyas/seo` to 2.1.0?

```bash
npm install @hyas/images@latest
```

Did you clear the cache and then run the development server?

```
npm run clean:build && npm run dev
```
I cannot reproduce your issue — could you share your repo?
