### ISSUE TITLE
Blog Reactions

### ISSUE THREAD

**Issue by Rancho-rachit** [gethyas/doks#1201]
## Summary

- Like button below blog posts.
- Comment Section to have a thread like discussion

### Basic example

Reddit

### Motivation

- Helps to increase direct interaction between the viewer and the owner. 
- Also we can sort the blogs on the basis of likes

**Comment by h-enk** [comment]
I see the added value, but this is not something for Doks core — more likely an [Integration](https://docs.gethyas.com/guides/integrations/) or a [Recipe](https://getdoks.org/docs/recipes/).
