### ISSUE TITLE
Is there currently support for multiple content docs?

### ISSUE THREAD

**Issue by cnsync** [gethyas/doks#1205]
[[main]]
  name = "Docs"
  url = "/docs/runtime/overview/"
  weight = 10

[[main]]
  name = "Docs1"
  url = "/docs1/runtime/overview/"
  weight = 20

I can't get the sidebar to work as configured above, but it seems to only work with the docs directory.

**Comment by h-enk** [comment]
Did you add the `docs1` section to `doks.sectionNav` — see also  [Other main sections](https://getdoks.org/docs/basics/navigation/#other-main-sections)?

Also, make sure that your pages' `title`s are unique

**Comment by cnsync** [comment]
Hello I've found the configuration solution, set in params.toml sectionNav = ["docs", "docs1"] # ["docs"] (default) or list of sections (e.g. ["docs", "guides"])
