### ISSUE TITLE
Viewport between 992 and 1200 hides content

### ISSUE THREAD

**Issue by timcappalli** [gethyas/doks#1219]
## Description

When the viewport width is between 992 and 1200, the main content is hidden.

### Steps to reproduce

Go to https://passkeys.dev/docs/intro/what-are-passkeys/

Resize the window to a horizontal width between 992 and 1200

### Expected result

At this width, the menu should collapse allowing the main content to take up the full viewport

### Actual result

The main content is hidden while the menu remains.

![resize-example-gh](https://github.com/gethyas/doks/assets/6476604/995fe610-ef1a-4b48-a6fc-dd50dccba8c2)

### Environment

Paste the information here as shown by `npm run info`

```shell
{
  'passkeys.dev': '0.0.0',
  npm: '10.2.3',
  node: '18.19.0',
  acorn: '8.10.0',
  ada: '2.7.2',
  ares: '1.20.1',
  base64: '0.5.0',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '6.0.11',
  modules: '108',
  napi: '9',
  nghttp2: '1.57.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.12+quic',
  simdutf: '3.2.18',
  tz: '2023c',
  undici: '5.26.4',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.19',
  v8: '10.2.154.26-node.28',
  zlib: '1.2.13.1-motley'
}

> passkeys.dev@0.0.0 info
> npm list

passkeys.dev@0.0.0 /home/<<removed>>/passkeys.dev
├── @hyas/doks-core@1.4.1
├── @hyas/images@3.1.0
├── @hyas/inline-svg@1.0.5
├── @hyas/seo@2.2.0
├── @tabler/icons@2.47.0
├── auto-changelog@2.4.0
├── exec-bin@1.0.0
├── gethyas@2.2.2
├── hugo-installer@4.0.1
└── shx@0.3.4


> passkeys.dev@0.0.0 postinfo
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended linux/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio
```

**Comment by h-enk** [comment]
You're using a customized  `layouts/docs/single.html`. Replacing (the contents of) this one with the orignal [`_default/single.html`](https://github.com/gethyas/doks-core/blob/main/layouts/_default/single.html) fixes it

**Comment by timcappalli** [comment]
I restored to the original that you linked (cleaned and rebuilt as well) and unfortunately it didn't help.

<img width="1176" alt="image" src="https://github.com/gethyas/doks/assets/6476604/ac30b323-58c0-4add-bb0d-584083a13602">

**Comment by timcappalli** [comment]
I replaced `l/d/single.html` with the contents you referenced (and cleaned and rebuilt) and it didn't change the behavior.

<img width="1165" alt="image" src="https://github.com/gethyas/doks/assets/6476604/52e790a9-f295-43c8-bb3b-42b9215e40f1">

**Comment by timcappalli** [comment]
Thanks as always @h-enk. That worked!
