### ISSUE TITLE
Please change the default baseURL

### ISSUE THREAD

**Issue by frjo** [gethyas/doks#1223]
Please change this to something like `https://example.org/`. In the Hugo forums we get large number of new users that get in to trouble because they keep this example setting.

https://github.com/gethyas/doks/blob/2c955aefc3aa75f0f784e5008900a76c572b9e77/config/_default/hugo.toml#L2

**Comment by h-enk** [comment]
The new local default: https://github.com/gethyas/doks/blob/main/config/_default/hugo.toml#L2

Production URL set in: https://github.com/gethyas/doks/blob/main/config/production/hugo.toml
