### ISSUE TITLE
Add Algolia Search (next to FlexSearch) as an option

### ISSUE THREAD

**Issue by h-enk** [gethyas/doks#130]
## Summary

- [Algolia website](https://www.algolia.com/)

### Basic example

- [Site search on the JAMstack with Hugo & Algolia](https://www.bennet.org/blog/site-search-jamstack-hugo-algolia/)
- [getdoks.org](https://getdoks.org/)

### Motivation

- https://github.com/h-enk/doks/discussions/120

**Comment by NicoHood** [comment]
I am confused, why does getdoks.org already use algolia while this repo does not use it?

**Comment by teamcrisis** [comment]
@NicoHood see https://github.com/h-enk/doks/discussions/120 where we discuss this - I think the original motivation was to have a free search method but thoughts regarding search have changed recently.

**Comment by smythp** [comment]
It looks like you're switching how search is provided in Doks, but I wanted to inquire about the current state. By default, it doesn't seem like flexsearch works in a freshly cloned repo. I've tried changing the variables (using "ALL", etc., in the config), but the indexing variable seems to have no effect on behavior (though the show one works). Is there a command or similar I'm missing that builds the index? Should I just roll my own here for now?

Thanks, enjoying Doks.

**Comment by smythp** [comment]
The repo is here:

https://github.com/smythp/sigstore-docs-replatform

I've reenabled the search. The flex-related variables are set to empty lists, though I've gone through a number of permutations. Thank you for any guidance, I was going to set up another provider but I'd prefer to try to get the default for this theme working.

**Comment by h-enk** [comment]
It's an issue in the file that generates the index (it fails on an commented out part).

Delete these lines and you're good to go!

https://github.com/smythp/sigstore-docs-replatform/blob/main/assets/js/index.js#L78-L94

**Comment by h-enk** [comment]
Doks comes with FlexSearch preconfigured out of the box. If you want to use [DocSearch](https://docsearch.algolia.com/) in stead, [this guide](https://getdoks.org/docs/recipes/docsearch/) will explain how.
