### ISSUE TITLE
Add Mermaid theme switch respecting dark/light toggle

### ISSUE THREAD

**Issue by h-enk** [gethyas/doks#376]
## Summary

Add a Mermaid theme switch respecting the dark/light toggle. So, default Mermaid theme when toggled light, and dark Mermaid theme when toggled dark. 

### Basic example

See e.g. [Drawing diagrams in Sanity with Mermaid.js](https://raymondjulin.com/blog/drawing-diagrams-in-sanity-with-mermaid-js). 

### Motivation

Better dark mode support.

**Comment by h-enk** [comment]
Thanks! Interesting (didn't know that), I will have a look into that (I think it's possible).

**Comment by james-d-elliott** [comment]
I'm no web expert by any means, but wouldn't setting <body> `data-*` attributes using the JS which swiches themes then checking this value?

**Comment by h-enk** [comment]
Yes, presence of the `data-dark-mode` attribute on the `html` element could be used for this

**Comment by h-enk** [comment]
Or, check on the local storage item set:

```js
var theme = (localStorage.getItem('theme') === 'dark') ? "dark" : "default";
```
