### ISSUE TITLE
Add highlight.js theme as an option

### ISSUE THREAD

**Issue by h-enk** [gethyas/doks#699]
## Summary

Brief explanation of the feature.

### Basic example

Include a basic example or links here.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

https://github.com/h-enk/doks/discussions/87#discussioncomment-2255403

**Comment by imroc** [comment]
Is this WIP?

**Comment by h-enk** [comment]
Dropped for using Hugo's (faster) default (Chroma) syntax highlighting — on build
