### ISSUE TITLE
Image Shortcodes

### ISSUE THREAD

**Issue by CommanderStorm** [gethyas/doks#888]
## Description

I tried to add images with Subtiltles to our site. It turns out, that this feature has been dropped in a previous commit.
This could be related to https://github.com/h-enk/doks/issues/133, but I don't think it is, so I decided to add another issue.

### Steps to reproduce

1. copy image shortcode from https://getdoks.org/docs/tutorial/add-images/

### Expected result

Either no error, or this not being documented 😉 

### Actual result

![image](https://user-images.githubusercontent.com/26258709/188716289-14a7b822-57a8-4d18-859d-672947b8f5fd.png)

### Environment

Any commit after https://github.com/h-enk/doks/commit/24ad4ae339c9ebc76a2b35bde67555408eb2d706 is affected.

### Proposed fix:

Revert the mentioned commit and removed everything relating to `$lqip` and `lazySizes`.
I dont know why this fails though. Is this the reason you removed it?

**Comment by h-enk** [comment]
Thanks. It's just not documented yet (working on it). Doks now uses [h-enk/hyas-images](https://github.com/h-enk/hyas-images) which uses [danielfdickinson/image-handling-mod-hugo-dfd](https://github.com/danielfdickinson/image-handling-mod-hugo-dfd). For now, please check Daniel's repo.

I'll leave this issue open — as  a reminder to update the documentation 😉

**Comment by h-enk** [comment]
You can now use the [figure](https://images.gethyas.com/docs/shortcodes/figure/) shortcode
